import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/addon/header/page"
import Footer from "@/app/components/addon/footer/page"
import { CartProvider } from "@/app/context/cartContext"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <Header />
          <main className="bg-slate-100 flex-col items-center sm:items-start">
            {children}
          </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
